### ISSUE TITLE
does it work on macOS?

### ISSUE THREAD

**Issue by hugoledoux** [GeoplexGIS/geores#1]
When I tried to load the extension, nothing happens. No warnings, no errors. But the extension is not loaded.

Have you tried on other OS?

**Comment by lordi** [comment]
The plugin does work with macOS.

I created a Github release. Please try again with the `geores.rbz` at https://github.com/GeoplexGIS/geores/releases/tag/2.0.2

How did you create the rbz? Did you use the Github source download or did you zip the files manually?

**Comment by hugoledoux** [comment]
I had zipped the folder (cloned the repo) and changed its name. 

With the release it's working, cheers!

Interface is German-only, so I'll need more time to try it... But the import doesn't work for me, all XML/GML files can't be selected, this is weird.

**Comment by lordi** [comment]
You are right, MacOS SketchUp had a problem with the two extensions specified by the importer. I'll push create a new version that will have two separate importers for both `.xml` and `.gml`.

**Comment by lordi** [comment]
Should work with https://github.com/GeoplexGIS/geores/releases/tag/v2.0.3
Updating is a little bit of a hazzle with SketchUp. I think you need to uninstall the plugin, restart, and then install the new version.
